-- Even Fibonacci numbers
-- Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

module Problem_2 where


fibs :: [Int]
fibs = 1:scanl (\acc x -> acc + x) 2 fibs

fibsBelow :: Int -> [Int]
fibsBelow x = takeWhile (<x) fibs

sumOfEvenFibsBelow :: Int -> Int
sumOfEvenFibsBelow = sum . filter even . fibsBelow

problem2 :: Int
problem2 = sumOfEvenFibsBelow 4000000
